### ISSUE TITLE
ReferenceError: Node is not defined

### ISSUE THREAD

**Issue by mrinalraj** [ultraq/thymeleafjs#38]
Node not defined on trying to use the .process() function.

at serialize (.\node_modules\thymeleaf\lib\thymeleaf.node.cjs.js:710:33)

* node version - v12.18.2

**Comment by ultraq** [comment]
Hey there, thanks for the bug report.  I *think* I was able to figure out what might be going on without more info, and have uploaded a 0.20.1 version of thymeleafjs which addresses this.  Could you give that version a try and let me know if it fixes things for you?  (Unfortunately, I can't easily have a test that checks for this because Jest loads a DOM environment into Node globals and so `Node` is always present.)

**Comment by ultraq** [comment]
Fixed in 0.20.1
