### ISSUE TITLE
Templates : Unable to include or replace (but insert works fine)

### ISSUE THREAD

**Issue by aethernet** [ultraq/thymeleafjs#39]
Hi, 

Thanks for this lib.

I'm trying to use th:replace, but it doesn't works.
I'm working with gulp, gulp-thymeleaf and thymeleaf 0.20.1

th:insert works as intended, but when i try to replace or includes it does nothing.

Here's my template : 

```
<!DOCTYPE html>
<html>
	<body>
		<div id="website">
			<div th:replace="~{footer :: copy}"></div>
			<div th:include="~{footer :: copy}"></div>
			<div th:insert="~{footer :: copy}"></div>
		</div>
	</body>
</html>

```

and my fragment : 
```
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
  <body>
    <div th:fragment="copy">
      &copy; 2011 The Good Thymes Virtual Grocery
    </div>
  </body>
</html>
```

results in 
```
<!DOCTYPE html><html lang="en"><head></head><body lang="en">{{&gt; head}}
		<div id="website">
			<div th:replace="~{footer :: copy}"></div>
			<div th:include="~{footer :: copy}"></div>
			<div><div>
     © 2011 The Good Thymes Virtual Grocery
    </div></div>
		</div>
</body></html>
```

Any ideas ?

**Comment by ultraq** [comment]
`th:include` hasn't been added to this library as Thymeleaf 3 marked it as "not recommended" (https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#difference-between-thinsert-and-threplace-and-thinclude), so I didn't think to implement it.

As for `th:replace`, I'll have a look - that one should be a part of this library and working.

**Comment by ultraq** [comment]
I created a Jest test file with the templates you've given, and `th:replace` seems to work.  I did have to swap out `&copy;` as it replaced things with the © symbol, but otherwise it works as expected.  (Test file in referenced commit above this post.)

I then did a quick install of `gulp-thymeleaf` and I noticed it uses a very old version of this library, version 0.12.1.  I didn't add the `th:replace` processor until 0.14.0 (https://github.com/ultraq/thymeleafjs/blob/master/CHANGELOG.md#0140), so I think that's why it's not working.

It looks like an update in `gulp-thymeleaf` is needed, but I don't know where you need to file an issue / bug report to do that.  The package doesn't include a repository or webpage where you could do that 😕

**Comment by Cali88** [comment]
Thanks so much, 
I checked the version and i thought i was using the latest version of thjs
Looks like i looked at the wrong place!

I'll fork it, upgrade and make a PR to gulp-thymeleaf.

**Comment by aethernet** [comment]
Was logged in with a wrong account
Thank you :)

**Comment by aethernet** [comment]
Indeed works perfectly! 
Thanks so much

If anyone needs it, here's the fork : https://github.com/3000d/gulp-thymeleaf
Nothing changed but the thjs version.
